//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 05/09/2017 16:30:01
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace DigiTransit10.Localization.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class AppResources
    {
        
        private static ResourceLoader resourceLoader;
        
        static AppResources()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(AppResources).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("AppResources");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/AppResources");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "You haven't saved any favorites yet"
        /// </summary>
        public static string Favorites_EmptyList
        {
            get
            {
                return resourceLoader.GetString("Favorites_EmptyList");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Favorites"
        /// </summary>
        public static string Favorites_FavoritesHeader
        {
            get
            {
                return resourceLoader.GetString("Favorites_FavoritesHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Date"
        /// </summary>
        public static string LiteralDate
        {
            get
            {
                return resourceLoader.GetString("LiteralDate");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "From"
        /// </summary>
        public static string MainPage_FromHeader
        {
            get
            {
                return resourceLoader.GetString("MainPage_FromHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "TRIP PLANNING"
        /// </summary>
        public static string MainPage_Header
        {
            get
            {
                return resourceLoader.GetString("MainPage_Header");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "To"
        /// </summary>
        public static string MainPage_ToHeader
        {
            get
            {
                return resourceLoader.GetString("MainPage_ToHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Addresses"
        /// </summary>
        public static string SuggestBoxHeader_Addresses
        {
            get
            {
                return resourceLoader.GetString("SuggestBoxHeader_Addresses");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Transit Stops"
        /// </summary>
        public static string SuggestBoxHeader_TransitStops
        {
            get
            {
                return resourceLoader.GetString("SuggestBoxHeader_TransitStops");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Arrival"
        /// </summary>
        public static string TimeType_Arrival
        {
            get
            {
                return resourceLoader.GetString("TimeType_Arrival");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Departure"
        /// </summary>
        public static string TimeType_Departure
        {
            get
            {
                return resourceLoader.GetString("TimeType_Departure");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Arrival or departure time?"
        /// </summary>
        public static string TimeType_PlaceholderText
        {
            get
            {
                return resourceLoader.GetString("TimeType_PlaceholderText");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Plan a trip"
        /// </summary>
        public static string TripForm_PlanATripHeader
        {
            get
            {
                return resourceLoader.GetString("TripForm_PlanATripHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Planning..."
        /// </summary>
        public static string TripForm_PlanningTrip
        {
            get
            {
                return resourceLoader.GetString("TripForm_PlanningTrip");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Plan"
        /// </summary>
        public static string TripForm_PlanTripButton
        {
            get
            {
                return resourceLoader.GetString("TripForm_PlanTripButton");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Resolving locations..."
        /// </summary>
        public static string TripFrom_GettingsAddresses
        {
            get
            {
                return resourceLoader.GetString("TripFrom_GettingsAddresses");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Fewer options"
        /// </summary>
        public static string TripForm_FewerOptions
        {
            get
            {
                return resourceLoader.GetString("TripForm_FewerOptions");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "More options"
        /// </summary>
        public static string TripForm_MoreOptions
        {
            get
            {
                return resourceLoader.GetString("TripForm_MoreOptions");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Time"
        /// </summary>
        public static string LiteralTime
        {
            get
            {
                return resourceLoader.GetString("LiteralTime");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Transit types"
        /// </summary>
        public static string TripForm_TransitTypeHeader
        {
            get
            {
                return resourceLoader.GetString("TripForm_TransitTypeHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "My location"
        /// </summary>
        public static string SuggestBoxHeader_MyLocation
        {
            get
            {
                return resourceLoader.GetString("SuggestBoxHeader_MyLocation");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Now"
        /// </summary>
        public static string LiteralNow
        {
            get
            {
                return resourceLoader.GetString("LiteralNow");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Set to today"
        /// </summary>
        public static string TripForm_SetDateToNow
        {
            get
            {
                return resourceLoader.GetString("TripForm_SetDateToNow");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Set to now"
        /// </summary>
        public static string TripForm_SetTimeToNow
        {
            get
            {
                return resourceLoader.GetString("TripForm_SetTimeToNow");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Origin"
        /// </summary>
        public static string TripPlanStrip_StartingPlaceDefault
        {
            get
            {
                return resourceLoader.GetString("TripPlanStrip_StartingPlaceDefault");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Loading..."
        /// </summary>
        public static string LoadingLiteral
        {
            get
            {
                return resourceLoader.GetString("LoadingLiteral");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Destination"
        /// </summary>
        public static string TripPlanStrip_EndPlaceDefault
        {
            get
            {
                return resourceLoader.GetString("TripPlanStrip_EndPlaceDefault");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Delete"
        /// </summary>
        public static string LiteralDelete
        {
            get
            {
                return resourceLoader.GetString("LiteralDelete");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Favorites"
        /// </summary>
        public static string SuggestBoxHeader_FavoritePlaces
        {
            get
            {
                return resourceLoader.GetString("SuggestBoxHeader_FavoritePlaces");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Now"
        /// </summary>
        public static string CurrentTimePicker_CurrentTime
        {
            get
            {
                return resourceLoader.GetString("CurrentTimePicker_CurrentTime");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Pinned favorites"
        /// </summary>
        public static string TripForm_PinnedFavoritesHeader
        {
            get
            {
                return resourceLoader.GetString("TripForm_PinnedFavoritesHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Trip plans"
        /// </summary>
        public static string TripResults_TripPlansHeader
        {
            get
            {
                return resourceLoader.GetString("TripResults_TripPlansHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No routes found. Check your search parameters."
        /// </summary>
        public static string DialogMessage_NoTripsFoundNoResults
        {
            get
            {
                return resourceLoader.GetString("DialogMessage_NoTripsFoundNoResults");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No routes found, because a connection with the server couldn't be established. Check your internet connection, or try again later."
        /// </summary>
        public static string DialogMessage_NoTripsFoundNoServer
        {
            get
            {
                return resourceLoader.GetString("DialogMessage_NoTripsFoundNoServer");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No routes found. Please try again."
        /// </summary>
        public static string DialogMessage_NoTripsFoundUnknown
        {
            get
            {
                return resourceLoader.GetString("DialogMessage_NoTripsFoundUnknown");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "We were unable to locate the following places:"
        /// </summary>
        public static string DialogMessage_PlaceResolutionFailed
        {
            get
            {
                return resourceLoader.GetString("DialogMessage_PlaceResolutionFailed");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "We were unable to locate you. Are location services enabled for this app?"
        /// </summary>
        public static string DialogMessage_UserLocationFailed
        {
            get
            {
                return resourceLoader.GetString("DialogMessage_UserLocationFailed");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Location failure"
        /// </summary>
        public static string DialogTitle_NoLocationFound
        {
            get
            {
                return resourceLoader.GetString("DialogTitle_NoLocationFound");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No routes found"
        /// </summary>
        public static string DialogTitle_NoTripsFound
        {
            get
            {
                return resourceLoader.GetString("DialogTitle_NoTripsFound");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Add favorite"
        /// </summary>
        public static string FavoritesPage_CommandBarAddFavorite
        {
            get
            {
                return resourceLoader.GetString("FavoritesPage_CommandBarAddFavorite");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "FAVORITES"
        /// </summary>
        public static string FavoritesPage_PageHeader
        {
            get
            {
                return resourceLoader.GetString("FavoritesPage_PageHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Favorites"
        /// </summary>
        public static string NavigationLabels_Favorites
        {
            get
            {
                return resourceLoader.GetString("NavigationLabels_Favorites");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Home"
        /// </summary>
        public static string NavigationLabels_Home
        {
            get
            {
                return resourceLoader.GetString("NavigationLabels_Home");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Search"
        /// </summary>
        public static string NavigationLabels_Search
        {
            get
            {
                return resourceLoader.GetString("NavigationLabels_Search");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Settings"
        /// </summary>
        public static string NavigationLabels_Settings
        {
            get
            {
                return resourceLoader.GetString("NavigationLabels_Settings");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Places"
        /// </summary>
        public static string Favorites_PlacesGroupHeader
        {
            get
            {
                return resourceLoader.GetString("Favorites_PlacesGroupHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Routes"
        /// </summary>
        public static string Favorites_RoutesGroupHeader
        {
            get
            {
                return resourceLoader.GetString("Favorites_RoutesGroupHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Details"
        /// </summary>
        public static string TripResultCommandBar_Details
        {
            get
            {
                return resourceLoader.GetString("TripResultCommandBar_Details");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Map"
        /// </summary>
        public static string TripResultCommandBar_Map
        {
            get
            {
                return resourceLoader.GetString("TripResultCommandBar_Map");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Unpin"
        /// </summary>
        public static string PinnedFavoritesList_Unpin
        {
            get
            {
                return resourceLoader.GetString("PinnedFavoritesList_Unpin");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "intermediate stop(s)"
        /// </summary>
        public static string TripDetailListIntermediates_IntermediateStopsNumber
        {
            get
            {
                return resourceLoader.GetString("TripDetailListIntermediates_IntermediateStopsNumber");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Walk {0} meters"
        /// </summary>
        public static string TripDetailListIntermediates_WalkDistance
        {
            get
            {
                return resourceLoader.GetString("TripDetailListIntermediates_WalkDistance");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Travel {0} meters"
        /// </summary>
        public static string TripDetailListIntermediates_TransitDistance
        {
            get
            {
                return resourceLoader.GetString("TripDetailListIntermediates_TransitDistance");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "+ Add intermediate destination"
        /// </summary>
        public static string MainPage_AddIntermediateDestination
        {
            get
            {
                return resourceLoader.GetString("MainPage_AddIntermediateDestination");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Save route"
        /// </summary>
        public static string TripResults_SaveRoute
        {
            get
            {
                return resourceLoader.GetString("TripResults_SaveRoute");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Add Favorite"
        /// </summary>
        public static string AddOrEditFavoriteDialog_AddHeader
        {
            get
            {
                return resourceLoader.GetString("AddOrEditFavoriteDialog_AddHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Cancel"
        /// </summary>
        public static string AddOrEditFavoriteDialog_Cancel
        {
            get
            {
                return resourceLoader.GetString("AddOrEditFavoriteDialog_Cancel");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Edit Favorite"
        /// </summary>
        public static string AddOrEditFavoriteDialog_EditHeader
        {
            get
            {
                return resourceLoader.GetString("AddOrEditFavoriteDialog_EditHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Icon"
        /// </summary>
        public static string AddOrEditFavoriteDialog_IconsHeader
        {
            get
            {
                return resourceLoader.GetString("AddOrEditFavoriteDialog_IconsHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Save"
        /// </summary>
        public static string AddOrEditFavoriteDialog_Save
        {
            get
            {
                return resourceLoader.GetString("AddOrEditFavoriteDialog_Save");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Location"
        /// </summary>
        public static string AddOrEditFavoriteDialog_SearchBoxHeader
        {
            get
            {
                return resourceLoader.GetString("AddOrEditFavoriteDialog_SearchBoxHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Name"
        /// </summary>
        public static string AddOrEditFavoriteDialog_UserChosenNameHeader
        {
            get
            {
                return resourceLoader.GetString("AddOrEditFavoriteDialog_UserChosenNameHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Select"
        /// </summary>
        public static string FavoritesPage_CommandBarSelect
        {
            get
            {
                return resourceLoader.GetString("FavoritesPage_CommandBarSelect");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "is already pinned to Start!"
        /// </summary>
        public static string Favorites_PinToStartAlreadyExists
        {
            get
            {
                return resourceLoader.GetString("Favorites_PinToStartAlreadyExists");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Could not pin to Start"
        /// </summary>
        public static string Favorites_PinToStartErrorTitle
        {
            get
            {
                return resourceLoader.GetString("Favorites_PinToStartErrorTitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Not sure why, but we weren't able to pin {0} to Start."
        /// </summary>
        public static string Favorites_PinToStartGenericFailure
        {
            get
            {
                return resourceLoader.GetString("Favorites_PinToStartGenericFailure");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Delete Selected"
        /// </summary>
        public static string FavoritesPage_CommandBarDeleteSelected
        {
            get
            {
                return resourceLoader.GetString("FavoritesPage_CommandBarDeleteSelected");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Pin to Start"
        /// </summary>
        public static string LiteralPinToStart
        {
            get
            {
                return resourceLoader.GetString("LiteralPinToStart");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "SEARCH"
        /// </summary>
        public static string SearchPage_Header
        {
            get
            {
                return resourceLoader.GetString("SearchPage_Header");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Lines"
        /// </summary>
        public static string SearchPage_LinesHeader
        {
            get
            {
                return resourceLoader.GetString("SearchPage_LinesHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Nearby"
        /// </summary>
        public static string SearchPage_NearbyHeader
        {
            get
            {
                return resourceLoader.GetString("SearchPage_NearbyHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Stops"
        /// </summary>
        public static string SearchPage_StopsHeader
        {
            get
            {
                return resourceLoader.GetString("SearchPage_StopsHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Find stops near this point"
        /// </summary>
        public static string SearchPage_MapContextMenuFindPlacesHere
        {
            get
            {
                return resourceLoader.GetString("SearchPage_MapContextMenuFindPlacesHere");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Find stops near me"
        /// </summary>
        public static string SearchPage_MapContextFindPlacesAtMe
        {
            get
            {
                return resourceLoader.GetString("SearchPage_MapContextFindPlacesAtMe");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Add to favorites"
        /// </summary>
        public static string Flyout_AddToFavorites
        {
            get
            {
                return resourceLoader.GetString("Flyout_AddToFavorites");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Edit"
        /// </summary>
        public static string Flyout_Edit
        {
            get
            {
                return resourceLoader.GetString("Flyout_Edit");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Main page"
        /// </summary>
        public static string Flyout_MainPage
        {
            get
            {
                return resourceLoader.GetString("Flyout_MainPage");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Pin to..."
        /// </summary>
        public static string Flyout_PinTo
        {
            get
            {
                return resourceLoader.GetString("Flyout_PinTo");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Select"
        /// </summary>
        public static string Flyout_Select
        {
            get
            {
                return resourceLoader.GetString("Flyout_Select");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Set as destination"
        /// </summary>
        public static string Flyout_SetAsDestination
        {
            get
            {
                return resourceLoader.GetString("Flyout_SetAsDestination");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Set as origin"
        /// </summary>
        public static string Flyout_SetAsOrigin
        {
            get
            {
                return resourceLoader.GetString("Flyout_SetAsOrigin");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Start"
        /// </summary>
        public static string Flyout_Start
        {
            get
            {
                return resourceLoader.GetString("Flyout_Start");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "View stop details"
        /// </summary>
        public static string StopSearchElement_ViewDetails
        {
            get
            {
                return resourceLoader.GetString("StopSearchElement_ViewDetails");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Upcoming Departures"
        /// </summary>
        public static string StopSearchContent_DetailsDeparturesHeader
        {
            get
            {
                return resourceLoader.GetString("StopSearchContent_DetailsDeparturesHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Lines"
        /// </summary>
        public static string StopSearchContent_DetailsLinesHeader
        {
            get
            {
                return resourceLoader.GetString("StopSearchContent_DetailsLinesHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Unable to retreive information from the server. It's reporting that service is currently unavailable. Try agin later."
        /// </summary>
        public static string DialogMessage_NoTripsFoundServerDown
        {
            get
            {
                return resourceLoader.GetString("DialogMessage_NoTripsFoundServerDown");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Today"
        /// </summary>
        public static string CurrentDatePicker_CurrentDate
        {
            get
            {
                return resourceLoader.GetString("CurrentDatePicker_CurrentDate");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Looks like there aren't any more upcoming departures today"
        /// </summary>
        public static string StopSearchContent_DetailsEmptyDeparturesListHeader
        {
            get
            {
                return resourceLoader.GetString("StopSearchContent_DetailsEmptyDeparturesListHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "If enabled, this will send anonymous usage information to the developer. He can use that to make future versions of the app better! =)
        ///(or abandon features that no one uses)"
        /// </summary>
        public static string SettingsPage_AnalyticsExplanation
        {
            get
            {
                return resourceLoader.GetString("SettingsPage_AnalyticsExplanation");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Analytics & telemetry"
        /// </summary>
        public static string SettingsPage_AnalyticsHeader
        {
            get
            {
                return resourceLoader.GetString("SettingsPage_AnalyticsHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Tracking"
        /// </summary>
        public static string SettingsPage_AnalyticsToggleHeader
        {
            get
            {
                return resourceLoader.GetString("SettingsPage_AnalyticsToggleHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "You can set your default To and From locations, as well as the default route optimization settings. These settings will be used to populate the search page when opening the app."
        /// </summary>
        public static string SettingsPage_DefaultSearchExplanation
        {
            get
            {
                return resourceLoader.GetString("SettingsPage_DefaultSearchExplanation");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Default search options"
        /// </summary>
        public static string SettingsPage_DefaultSearchHeader
        {
            get
            {
                return resourceLoader.GetString("SettingsPage_DefaultSearchHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "From"
        /// </summary>
        public static string SettingsPage_FromBoxHeader
        {
            get
            {
                return resourceLoader.GetString("SettingsPage_FromBoxHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "SETTINGS"
        /// </summary>
        public static string SettingsPage_PageHeader
        {
            get
            {
                return resourceLoader.GetString("SettingsPage_PageHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "To"
        /// </summary>
        public static string SettingsPage_ToBoxHeader
        {
            get
            {
                return resourceLoader.GetString("SettingsPage_ToBoxHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Amount of walking"
        /// </summary>
        public static string SettingsPage_WalkingAmountHeader
        {
            get
            {
                return resourceLoader.GetString("SettingsPage_WalkingAmountHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Walking speed"
        /// </summary>
        public static string SettingsPage_WalkingSpeedHeader
        {
            get
            {
                return resourceLoader.GetString("SettingsPage_WalkingSpeedHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Bare minimum"
        /// </summary>
        public static string WalkingAmount_0
        {
            get
            {
                return resourceLoader.GetString("WalkingAmount_0");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Some"
        /// </summary>
        public static string WalkingAmount_1
        {
            get
            {
                return resourceLoader.GetString("WalkingAmount_1");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Normal"
        /// </summary>
        public static string WalkingAmount_2
        {
            get
            {
                return resourceLoader.GetString("WalkingAmount_2");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Lots"
        /// </summary>
        public static string WalkingAmount_3
        {
            get
            {
                return resourceLoader.GetString("WalkingAmount_3");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Maximum"
        /// </summary>
        public static string WalkingAmount_4
        {
            get
            {
                return resourceLoader.GetString("WalkingAmount_4");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Glacial"
        /// </summary>
        public static string WalkingSpeed_0
        {
            get
            {
                return resourceLoader.GetString("WalkingSpeed_0");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "30 m/min"
        /// </summary>
        public static string WalkingSpeed_0_Subtitle
        {
            get
            {
                return resourceLoader.GetString("WalkingSpeed_0_Subtitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Slow"
        /// </summary>
        public static string WalkingSpeed_1
        {
            get
            {
                return resourceLoader.GetString("WalkingSpeed_1");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "50 m/min"
        /// </summary>
        public static string WalkingSpeed_1_Subtitle
        {
            get
            {
                return resourceLoader.GetString("WalkingSpeed_1_Subtitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Normal"
        /// </summary>
        public static string WalkingSpeed_2
        {
            get
            {
                return resourceLoader.GetString("WalkingSpeed_2");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "72 m/min"
        /// </summary>
        public static string WalkingSpeed_2_Subtitle
        {
            get
            {
                return resourceLoader.GetString("WalkingSpeed_2_Subtitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Fast"
        /// </summary>
        public static string WalkingSpeed_3
        {
            get
            {
                return resourceLoader.GetString("WalkingSpeed_3");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "125 m/min"
        /// </summary>
        public static string WalkingSpeed_3_Subtitle
        {
            get
            {
                return resourceLoader.GetString("WalkingSpeed_3_Subtitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Breakneck"
        /// </summary>
        public static string WalkingSpeed_4
        {
            get
            {
                return resourceLoader.GetString("WalkingSpeed_4");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "180 m/min"
        /// </summary>
        public static string WalkingSpeed_4_Subtitle
        {
            get
            {
                return resourceLoader.GetString("WalkingSpeed_4_Subtitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Licenses"
        /// </summary>
        public static string SettingsPage_LicensesHeader
        {
            get
            {
                return resourceLoader.GetString("SettingsPage_LicensesHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "todo"
        /// </summary>
        public static string SettingsPage_LicensesText
        {
            get
            {
                return resourceLoader.GetString("SettingsPage_LicensesText");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Special thanks"
        /// </summary>
        public static string SettingsPage_SpecialThanksHeader
        {
            get
            {
                return resourceLoader.GetString("SettingsPage_SpecialThanksHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "todo"
        /// </summary>
        public static string SettingsPage_SpecialThanksText
        {
            get
            {
                return resourceLoader.GetString("SettingsPage_SpecialThanksText");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Set your chosen application theme."
        /// </summary>
        public static string SettingsPage_ThemeExplanation
        {
            get
            {
                return resourceLoader.GetString("SettingsPage_ThemeExplanation");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Theme"
        /// </summary>
        public static string SettingsPage_ThemeHeader
        {
            get
            {
                return resourceLoader.GetString("SettingsPage_ThemeHeader");
            }
        }

        /// <summary>
        /// Localized resource similar to "Light"
        /// </summary>
        public static string LightThemeName
        {
            get
            {
                return resourceLoader.GetString("LightThemeName");
            }
        }

        /// <summary>
        /// Localized resource similar to "Dark"
        /// </summary>
        public static string DarkThemeName
        {
            get
            {
                return resourceLoader.GetString("DarkThemeName");
            }
        }

        /// <summary>
        /// Localized resource similar to "System Default"
        /// </summary>
        public static string SystemSettingThemeName
        {
            get
            {
                return resourceLoader.GetString("SystemSettingThemeName");
            }
        }

        /// <summary>
        /// Localized resource similar to "Display theme"
        /// </summary>
        public static string SettingsPage_ThemeComboBoxHeader => resourceLoader.GetString(nameof(SettingsPage_ThemeComboBoxHeader));

        /// <summary>
        /// Localized resource similar to "Favorites"
        /// </summary>
        public static string SettingsPage_FavoritesPanelHeader => resourceLoader.GetString(nameof(SettingsPage_FavoritesPanelHeader));

        /// <summary>
        /// Localized resource similar to "Number of pinned favorites"
        /// </summary>
        public static string SettingsPage_PinnedFavoritesNumberComboBoxHeader => resourceLoader.GetString(nameof(SettingsPage_PinnedFavoritesNumberComboBoxHeader));

        /// <summary>
        /// Localized resource similar to "Set the maximum number of pinned favorites to display on the main page of the app. Default: 3"
        /// </summary>
        public static string SettingsPage_FavoritesPanelExplanation => resourceLoader.GetString(nameof(SettingsPage_FavoritesPanelExplanation));

        /// <summary>
        /// Localized resource similar to "Walking speed"
        /// </summary>
        public static string TripForm_WalkingSpeedHeader => resourceLoader.GetString(nameof(TripForm_WalkingSpeedHeader));

        /// <summary>
        /// Localized resource similar to "Walking amount"
        /// </summary>
        public static string TripForm_WalkingAmountHeader => resourceLoader.GetString(nameof(TripForm_WalkingAmountHeader));

        /// <summary>
        /// Localized resource similar to "Alerts"
        /// </summary>
        public static string MainPageHeaderCommand_Alerts => resourceLoader.GetString(nameof(MainPageHeaderCommand_Alerts));


    }
}
