//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://bit.ly/reswcodegen)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 03/13/2023 18:11:37
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Trippit.Localization.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    public sealed partial class AppResources
    {
        
        private static ResourceLoader resourceLoader;
        
        /// <summary>
        /// Get or set ResourceLoader implementation
        /// </summary>
        public static ResourceLoader Resource
        {
            get
            {
                if ((resourceLoader == null))
                {
                    AppResources.Initialize();
                }
                return resourceLoader;
            }
            set
            {
                resourceLoader = value;
            }
        }
        
        /// <summary>
        /// Localized resource similar to "You haven't saved any favorites yet"
        /// </summary>
        public static string Favorites_EmptyList
        {
            get
            {
                return Resource.GetString("Favorites_EmptyList");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Favorites"
        /// </summary>
        public static string Favorites_FavoritesHeader
        {
            get
            {
                return Resource.GetString("Favorites_FavoritesHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Date"
        /// </summary>
        public static string LiteralDate
        {
            get
            {
                return Resource.GetString("LiteralDate");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "From"
        /// </summary>
        public static string MainPage_FromHeader
        {
            get
            {
                return Resource.GetString("MainPage_FromHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "TRIP PLANNING"
        /// </summary>
        public static string MainPage_Header
        {
            get
            {
                return Resource.GetString("MainPage_Header");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "To"
        /// </summary>
        public static string MainPage_ToHeader
        {
            get
            {
                return Resource.GetString("MainPage_ToHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Arrival"
        /// </summary>
        public static string TimeType_Arrival
        {
            get
            {
                return Resource.GetString("TimeType_Arrival");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Departure"
        /// </summary>
        public static string TimeType_Departure
        {
            get
            {
                return Resource.GetString("TimeType_Departure");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Plan a trip"
        /// </summary>
        public static string TripForm_PlanATripHeader
        {
            get
            {
                return Resource.GetString("TripForm_PlanATripHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Planning..."
        /// </summary>
        public static string TripForm_PlanningTrip
        {
            get
            {
                return Resource.GetString("TripForm_PlanningTrip");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Plan"
        /// </summary>
        public static string TripForm_PlanTripButton
        {
            get
            {
                return Resource.GetString("TripForm_PlanTripButton");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Resolving locations..."
        /// </summary>
        public static string TripFrom_GettingsAddresses
        {
            get
            {
                return Resource.GetString("TripFrom_GettingsAddresses");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Fewer options"
        /// </summary>
        public static string TripForm_FewerOptions
        {
            get
            {
                return Resource.GetString("TripForm_FewerOptions");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "More options"
        /// </summary>
        public static string TripForm_MoreOptions
        {
            get
            {
                return Resource.GetString("TripForm_MoreOptions");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Time"
        /// </summary>
        public static string LiteralTime
        {
            get
            {
                return Resource.GetString("LiteralTime");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Transit types"
        /// </summary>
        public static string TripForm_TransitTypeHeader
        {
            get
            {
                return Resource.GetString("TripForm_TransitTypeHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Now"
        /// </summary>
        public static string LiteralNow
        {
            get
            {
                return Resource.GetString("LiteralNow");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Set to today"
        /// </summary>
        public static string TripForm_SetDateToNow
        {
            get
            {
                return Resource.GetString("TripForm_SetDateToNow");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Set to now"
        /// </summary>
        public static string TripForm_SetTimeToNow
        {
            get
            {
                return Resource.GetString("TripForm_SetTimeToNow");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Origin"
        /// </summary>
        public static string TripPlanStrip_StartingPlaceDefault
        {
            get
            {
                return Resource.GetString("TripPlanStrip_StartingPlaceDefault");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Loading..."
        /// </summary>
        public static string LoadingLiteral
        {
            get
            {
                return Resource.GetString("LoadingLiteral");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Destination"
        /// </summary>
        public static string TripPlanStrip_EndPlaceDefault
        {
            get
            {
                return Resource.GetString("TripPlanStrip_EndPlaceDefault");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Delete"
        /// </summary>
        public static string LiteralDelete
        {
            get
            {
                return Resource.GetString("LiteralDelete");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Now"
        /// </summary>
        public static string CurrentTimePicker_CurrentTime
        {
            get
            {
                return Resource.GetString("CurrentTimePicker_CurrentTime");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Pinned favorites"
        /// </summary>
        public static string TripForm_PinnedFavoritesHeader
        {
            get
            {
                return Resource.GetString("TripForm_PinnedFavoritesHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Trip plans"
        /// </summary>
        public static string TripResults_TripPlansHeader
        {
            get
            {
                return Resource.GetString("TripResults_TripPlansHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No routes found. Check your search parameters."
        /// </summary>
        public static string DialogMessage_NoTripsFoundNoResults
        {
            get
            {
                return Resource.GetString("DialogMessage_NoTripsFoundNoResults");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No routes found, because a connection with the server couldn't be established. Check your internet connection, or try again later."
        /// </summary>
        public static string DialogMessage_NoTripsFoundNoServer
        {
            get
            {
                return Resource.GetString("DialogMessage_NoTripsFoundNoServer");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No routes found. Please try again."
        /// </summary>
        public static string DialogMessage_NoTripsFoundUnknown
        {
            get
            {
                return Resource.GetString("DialogMessage_NoTripsFoundUnknown");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "We were unable to locate the following places:"
        /// </summary>
        public static string DialogMessage_PlaceResolutionFailed
        {
            get
            {
                return Resource.GetString("DialogMessage_PlaceResolutionFailed");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "We were unable to locate you. Are location services enabled for this app?"
        /// </summary>
        public static string DialogMessage_UserLocationFailed
        {
            get
            {
                return Resource.GetString("DialogMessage_UserLocationFailed");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Location failure"
        /// </summary>
        public static string DialogTitle_NoLocationFound
        {
            get
            {
                return Resource.GetString("DialogTitle_NoLocationFound");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No routes found"
        /// </summary>
        public static string DialogTitle_NoTripsFound
        {
            get
            {
                return Resource.GetString("DialogTitle_NoTripsFound");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Add favorite"
        /// </summary>
        public static string FavoritesPage_CommandBarAddFavorite
        {
            get
            {
                return Resource.GetString("FavoritesPage_CommandBarAddFavorite");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "FAVORITES"
        /// </summary>
        public static string FavoritesPage_PageHeader
        {
            get
            {
                return Resource.GetString("FavoritesPage_PageHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Favorites"
        /// </summary>
        public static string NavigationLabels_Favorites
        {
            get
            {
                return Resource.GetString("NavigationLabels_Favorites");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Home"
        /// </summary>
        public static string NavigationLabels_Home
        {
            get
            {
                return Resource.GetString("NavigationLabels_Home");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Search"
        /// </summary>
        public static string NavigationLabels_Search
        {
            get
            {
                return Resource.GetString("NavigationLabels_Search");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Settings"
        /// </summary>
        public static string NavigationLabels_Settings
        {
            get
            {
                return Resource.GetString("NavigationLabels_Settings");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Places"
        /// </summary>
        public static string Favorites_PlacesGroupHeader
        {
            get
            {
                return Resource.GetString("Favorites_PlacesGroupHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Routes"
        /// </summary>
        public static string Favorites_RoutesGroupHeader
        {
            get
            {
                return Resource.GetString("Favorites_RoutesGroupHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Details"
        /// </summary>
        public static string TripResultCommandBar_Details
        {
            get
            {
                return Resource.GetString("TripResultCommandBar_Details");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Map"
        /// </summary>
        public static string TripResultCommandBar_Map
        {
            get
            {
                return Resource.GetString("TripResultCommandBar_Map");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Unpin"
        /// </summary>
        public static string PinnedFavoritesList_Unpin
        {
            get
            {
                return Resource.GetString("PinnedFavoritesList_Unpin");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "intermediate stop(s)"
        /// </summary>
        public static string TripDetailListIntermediates_IntermediateStopsNumber
        {
            get
            {
                return Resource.GetString("TripDetailListIntermediates_IntermediateStopsNumber");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Walk {0} meters"
        /// </summary>
        public static string TripDetailListIntermediates_WalkDistance
        {
            get
            {
                return Resource.GetString("TripDetailListIntermediates_WalkDistance");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Travel {0} meters"
        /// </summary>
        public static string TripDetailListIntermediates_TransitDistance
        {
            get
            {
                return Resource.GetString("TripDetailListIntermediates_TransitDistance");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "+ Add intermediate destination"
        /// </summary>
        public static string MainPage_AddIntermediateDestination
        {
            get
            {
                return Resource.GetString("MainPage_AddIntermediateDestination");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Save route"
        /// </summary>
        public static string TripResults_SaveRoute
        {
            get
            {
                return Resource.GetString("TripResults_SaveRoute");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Add Favorite"
        /// </summary>
        public static string AddOrEditFavoriteDialog_AddHeader
        {
            get
            {
                return Resource.GetString("AddOrEditFavoriteDialog_AddHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Cancel"
        /// </summary>
        public static string AddOrEditFavoriteDialog_Cancel
        {
            get
            {
                return Resource.GetString("AddOrEditFavoriteDialog_Cancel");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Edit Favorite"
        /// </summary>
        public static string AddOrEditFavoriteDialog_EditHeader
        {
            get
            {
                return Resource.GetString("AddOrEditFavoriteDialog_EditHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Icon"
        /// </summary>
        public static string AddOrEditFavoriteDialog_IconsHeader
        {
            get
            {
                return Resource.GetString("AddOrEditFavoriteDialog_IconsHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Save"
        /// </summary>
        public static string AddOrEditFavoriteDialog_Save
        {
            get
            {
                return Resource.GetString("AddOrEditFavoriteDialog_Save");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Location"
        /// </summary>
        public static string AddOrEditFavoriteDialog_SearchBoxHeader
        {
            get
            {
                return Resource.GetString("AddOrEditFavoriteDialog_SearchBoxHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Name"
        /// </summary>
        public static string AddOrEditFavoriteDialog_UserChosenNameHeader
        {
            get
            {
                return Resource.GetString("AddOrEditFavoriteDialog_UserChosenNameHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Select"
        /// </summary>
        public static string FavoritesPage_CommandBarSelect
        {
            get
            {
                return Resource.GetString("FavoritesPage_CommandBarSelect");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "is already pinned to Start!"
        /// </summary>
        public static string Favorites_PinToStartAlreadyExists
        {
            get
            {
                return Resource.GetString("Favorites_PinToStartAlreadyExists");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Could not pin to Start"
        /// </summary>
        public static string Favorites_PinToStartErrorTitle
        {
            get
            {
                return Resource.GetString("Favorites_PinToStartErrorTitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Not sure why, but we weren't able to pin {0} to Start."
        /// </summary>
        public static string Favorites_PinToStartGenericFailure
        {
            get
            {
                return Resource.GetString("Favorites_PinToStartGenericFailure");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Delete Selected"
        /// </summary>
        public static string FavoritesPage_CommandBarDeleteSelected
        {
            get
            {
                return Resource.GetString("FavoritesPage_CommandBarDeleteSelected");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Pin to Start"
        /// </summary>
        public static string LiteralPinToStart
        {
            get
            {
                return Resource.GetString("LiteralPinToStart");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "SEARCH"
        /// </summary>
        public static string SearchPage_Header
        {
            get
            {
                return Resource.GetString("SearchPage_Header");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Lines"
        /// </summary>
        public static string SearchPage_LinesHeader
        {
            get
            {
                return Resource.GetString("SearchPage_LinesHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Nearby"
        /// </summary>
        public static string SearchPage_NearbyHeader
        {
            get
            {
                return Resource.GetString("SearchPage_NearbyHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Stops"
        /// </summary>
        public static string SearchPage_StopsHeader
        {
            get
            {
                return Resource.GetString("SearchPage_StopsHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Find stops near this point"
        /// </summary>
        public static string SearchPage_MapContextMenuFindPlacesHere
        {
            get
            {
                return Resource.GetString("SearchPage_MapContextMenuFindPlacesHere");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Find stops near me"
        /// </summary>
        public static string SearchPage_MapContextFindPlacesAtMe
        {
            get
            {
                return Resource.GetString("SearchPage_MapContextFindPlacesAtMe");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Add to favorites"
        /// </summary>
        public static string Flyout_AddToFavorites
        {
            get
            {
                return Resource.GetString("Flyout_AddToFavorites");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Edit"
        /// </summary>
        public static string Flyout_Edit
        {
            get
            {
                return Resource.GetString("Flyout_Edit");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Home page"
        /// </summary>
        public static string Flyout_MainPage
        {
            get
            {
                return Resource.GetString("Flyout_MainPage");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Pin to..."
        /// </summary>
        public static string Flyout_PinTo
        {
            get
            {
                return Resource.GetString("Flyout_PinTo");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Select"
        /// </summary>
        public static string Flyout_Select
        {
            get
            {
                return Resource.GetString("Flyout_Select");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Set as destination"
        /// </summary>
        public static string Flyout_SetAsDestination
        {
            get
            {
                return Resource.GetString("Flyout_SetAsDestination");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Set as origin"
        /// </summary>
        public static string Flyout_SetAsOrigin
        {
            get
            {
                return Resource.GetString("Flyout_SetAsOrigin");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Start"
        /// </summary>
        public static string Flyout_Start
        {
            get
            {
                return Resource.GetString("Flyout_Start");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "View stop details"
        /// </summary>
        public static string StopSearchElement_ViewDetails
        {
            get
            {
                return Resource.GetString("StopSearchElement_ViewDetails");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Upcoming Departures"
        /// </summary>
        public static string StopSearchContent_DetailsDeparturesHeader
        {
            get
            {
                return Resource.GetString("StopSearchContent_DetailsDeparturesHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Lines"
        /// </summary>
        public static string StopSearchContent_DetailsLinesHeader
        {
            get
            {
                return Resource.GetString("StopSearchContent_DetailsLinesHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Unable to retrieve information from the server. It's reporting that service is currently unavailable. Try again later."
        /// </summary>
        public static string DialogMessage_NoTripsFoundServerDown
        {
            get
            {
                return Resource.GetString("DialogMessage_NoTripsFoundServerDown");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Today"
        /// </summary>
        public static string CurrentDatePicker_CurrentDate
        {
            get
            {
                return Resource.GetString("CurrentDatePicker_CurrentDate");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Looks like there aren't any more upcoming departures today"
        /// </summary>
        public static string StopSearchContent_DetailsEmptyDeparturesListHeader
        {
            get
            {
                return Resource.GetString("StopSearchContent_DetailsEmptyDeparturesListHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "If enabled, this will send anonymous usage information to the developer. He can use that to make future versions of the app better! =)
        ///(or abandon features that no one uses)"
        /// </summary>
        public static string SettingsPage_AnalyticsExplanation
        {
            get
            {
                return Resource.GetString("SettingsPage_AnalyticsExplanation");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Analytics & telemetry"
        /// </summary>
        public static string SettingsPage_AnalyticsHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_AnalyticsHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Tracking"
        /// </summary>
        public static string SettingsPage_AnalyticsToggleHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_AnalyticsToggleHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "You can set your default To and From locations, as well as the default route optimization settings. These settings will be used to populate the search page when opening the app."
        /// </summary>
        public static string SettingsPage_DefaultSearchExplanation
        {
            get
            {
                return Resource.GetString("SettingsPage_DefaultSearchExplanation");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Default search options"
        /// </summary>
        public static string SettingsPage_DefaultSearchHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_DefaultSearchHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "From"
        /// </summary>
        public static string SettingsPage_FromBoxHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_FromBoxHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "SETTINGS"
        /// </summary>
        public static string SettingsPage_PageHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_PageHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "To"
        /// </summary>
        public static string SettingsPage_ToBoxHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_ToBoxHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Amount of walking"
        /// </summary>
        public static string SettingsPage_WalkingAmountHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_WalkingAmountHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Walking speed"
        /// </summary>
        public static string SettingsPage_WalkingSpeedHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_WalkingSpeedHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Bare minimum"
        /// </summary>
        public static string WalkingAmount_0
        {
            get
            {
                return Resource.GetString("WalkingAmount_0");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Some"
        /// </summary>
        public static string WalkingAmount_1
        {
            get
            {
                return Resource.GetString("WalkingAmount_1");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Normal"
        /// </summary>
        public static string WalkingAmount_2
        {
            get
            {
                return Resource.GetString("WalkingAmount_2");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Lots"
        /// </summary>
        public static string WalkingAmount_3
        {
            get
            {
                return Resource.GetString("WalkingAmount_3");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Maximum"
        /// </summary>
        public static string WalkingAmount_4
        {
            get
            {
                return Resource.GetString("WalkingAmount_4");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Glacial"
        /// </summary>
        public static string WalkingSpeed_0
        {
            get
            {
                return Resource.GetString("WalkingSpeed_0");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "30 m/min"
        /// </summary>
        public static string WalkingSpeed_0_Subtitle
        {
            get
            {
                return Resource.GetString("WalkingSpeed_0_Subtitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Slow"
        /// </summary>
        public static string WalkingSpeed_1
        {
            get
            {
                return Resource.GetString("WalkingSpeed_1");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "50 m/min"
        /// </summary>
        public static string WalkingSpeed_1_Subtitle
        {
            get
            {
                return Resource.GetString("WalkingSpeed_1_Subtitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Normal"
        /// </summary>
        public static string WalkingSpeed_2
        {
            get
            {
                return Resource.GetString("WalkingSpeed_2");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "72 m/min"
        /// </summary>
        public static string WalkingSpeed_2_Subtitle
        {
            get
            {
                return Resource.GetString("WalkingSpeed_2_Subtitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Fast"
        /// </summary>
        public static string WalkingSpeed_3
        {
            get
            {
                return Resource.GetString("WalkingSpeed_3");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "125 m/min"
        /// </summary>
        public static string WalkingSpeed_3_Subtitle
        {
            get
            {
                return Resource.GetString("WalkingSpeed_3_Subtitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Breakneck"
        /// </summary>
        public static string WalkingSpeed_4
        {
            get
            {
                return Resource.GetString("WalkingSpeed_4");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "180 m/min"
        /// </summary>
        public static string WalkingSpeed_4_Subtitle
        {
            get
            {
                return Resource.GetString("WalkingSpeed_4_Subtitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Licenses"
        /// </summary>
        public static string SettingsPage_LicensesHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_LicensesHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "• Roslynator under the Apache 2.0 license
        ///• Template10 under the Apache 2.0 license
        ///• The HockeyApp SDK under the MIT license
        ///• MetroLog under the MIT license
        ///• The official XAML Behaviors library under the MIT license
        ///• MVVM Light under the MIT license
        ///• JSON.NET under the MIT license
        ///• The NotificationExtensions library under the MIT license"
        /// </summary>
        public static string SettingsPage_LicensesText
        {
            get
            {
                return Resource.GetString("SettingsPage_LicensesText");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Special thanks"
        /// </summary>
        public static string SettingsPage_SpecialThanksHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_SpecialThanksHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "• Kaisa. She knows why  ??
        ///• Olli Saarikivi, for his excellent Reitit app and freely-given advice
        ///• Alisa Suorava for the fantastic app icon
        ///• Teemu Turunen and everybody else who've made the Futurice Spice Program what it is
        ///• HSL for their open API and wealth of resources
        ///• You! For using this app!"
        /// </summary>
        public static string SettingsPage_SpecialThanksText
        {
            get
            {
                return Resource.GetString("SettingsPage_SpecialThanksText");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Set your chosen application theme."
        /// </summary>
        public static string SettingsPage_ThemeExplanation
        {
            get
            {
                return Resource.GetString("SettingsPage_ThemeExplanation");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Theme"
        /// </summary>
        public static string SettingsPage_ThemeHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_ThemeHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Dark"
        /// </summary>
        public static string DarkThemeName
        {
            get
            {
                return Resource.GetString("DarkThemeName");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Light"
        /// </summary>
        public static string LightThemeName
        {
            get
            {
                return Resource.GetString("LightThemeName");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Set the maximum number of pinned favorites to display on the Home page of the app.
        ///Default: 3"
        /// </summary>
        public static string SettingsPage_FavoritesPanelExplanation
        {
            get
            {
                return Resource.GetString("SettingsPage_FavoritesPanelExplanation");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Favorites"
        /// </summary>
        public static string SettingsPage_FavoritesPanelHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_FavoritesPanelHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Number of pinned favorites"
        /// </summary>
        public static string SettingsPage_PinnedFavoritesNumberComboBoxHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_PinnedFavoritesNumberComboBoxHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Display theme"
        /// </summary>
        public static string SettingsPage_ThemeComboBoxHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_ThemeComboBoxHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "System theme"
        /// </summary>
        public static string SystemSettingThemeName
        {
            get
            {
                return Resource.GetString("SystemSettingThemeName");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Walking amount"
        /// </summary>
        public static string TripForm_WalkingAmountHeader
        {
            get
            {
                return Resource.GetString("TripForm_WalkingAmountHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Walking speed"
        /// </summary>
        public static string TripForm_WalkingSpeedHeader
        {
            get
            {
                return Resource.GetString("TripForm_WalkingSpeedHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Alerts"
        /// </summary>
        public static string MainPageHeaderCommand_Alerts
        {
            get
            {
                return Resource.GetString("MainPageHeaderCommand_Alerts");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Version"
        /// </summary>
        public static string SettingsPage_VersionHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_VersionHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No, thanks"
        /// </summary>
        public static string TooFarIntoPastDialog_Cancel
        {
            get
            {
                return Resource.GetString("TooFarIntoPastDialog_Cancel");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Yes, please"
        /// </summary>
        public static string TooFarIntoPastDialog_Confirm
        {
            get
            {
                return Resource.GetString("TooFarIntoPastDialog_Confirm");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "You've selected a time in the past. Would you like to set your trip date to tomorrow?"
        /// </summary>
        public static string TooFarIntoPastDialog_Content
        {
            get
            {
                return Resource.GetString("TooFarIntoPastDialog_Content");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Don't show me this again"
        /// </summary>
        public static string TooFarIntoPastDialog_DontShowCheckbox
        {
            get
            {
                return Resource.GetString("TooFarIntoPastDialog_DontShowCheckbox");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "From now on, your trip dates will automatically be moved forward to tomorrow if you select a time in the past."
        /// </summary>
        public static string TooFarIntoPastDialog_DontShowInfo
        {
            get
            {
                return Resource.GetString("TooFarIntoPastDialog_DontShowInfo");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Are you a time traveler?"
        /// </summary>
        public static string TooFarIntoPastDialog_Title
        {
            get
            {
                return Resource.GetString("TooFarIntoPastDialog_Title");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Note: Your selected date and time are in the past."
        /// </summary>
        public static string MainPage_TimeInPastWarning
        {
            get
            {
                return Resource.GetString("MainPage_TimeInPastWarning");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Cancel"
        /// </summary>
        public static string LiteralCancel
        {
            get
            {
                return Resource.GetString("LiteralCancel");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Affects"
        /// </summary>
        public static string AlertsPage_Affects
        {
            get
            {
                return Resource.GetString("AlertsPage_Affects");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "To:"
        /// </summary>
        public static string AlertsPage_TimeEnd
        {
            get
            {
                return Resource.GetString("AlertsPage_TimeEnd");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "From:"
        /// </summary>
        public static string AlertsPage_TimeStart
        {
            get
            {
                return Resource.GetString("AlertsPage_TimeStart");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "View online"
        /// </summary>
        public static string AlertsPage_ViewOnline
        {
            get
            {
                return Resource.GetString("AlertsPage_ViewOnline");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Trippit"
        /// </summary>
        public static string AppName
        {
            get
            {
                return Resource.GetString("AppName");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Trippit it makes it easy to get around using public transit in the greater Helsinki area."
        /// </summary>
        public static string AppDescription
        {
            get
            {
                return Resource.GetString("AppDescription");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Addresses"
        /// </summary>
        public static string SuggestBoxHeader_Addresses
        {
            get
            {
                return Resource.GetString("SuggestBoxHeader_Addresses");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Favorites"
        /// </summary>
        public static string SuggestBoxHeader_FavoritePlaces
        {
            get
            {
                return Resource.GetString("SuggestBoxHeader_FavoritePlaces");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Favorites"
        /// </summary>
        public static string SuggestBoxHeader_FavoritePlaces1
        {
            get
            {
                return Resource.GetString("SuggestBoxHeader_FavoritePlaces1");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "My location"
        /// </summary>
        public static string SuggestBoxHeader_MyLocation
        {
            get
            {
                return Resource.GetString("SuggestBoxHeader_MyLocation");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "ALERTS"
        /// </summary>
        public static string AlertsPage_PageHeader
        {
            get
            {
                return Resource.GetString("AlertsPage_PageHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Stops"
        /// </summary>
        public static string SuggestBoxHeader_TransitStops
        {
            get
            {
                return Resource.GetString("SuggestBoxHeader_TransitStops");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Set as route"
        /// </summary>
        public static string Flyout_SetAsRoute
        {
            get
            {
                return Resource.GetString("Flyout_SetAsRoute");
            }
        }
        
        public static void Initialize()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(AppResources).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("AppResources");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/AppResources");
            }
        }
    }
}
