//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://bit.ly/reswcodegen)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 03/13/2023 18:11:02
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Trippit.Localization.Strings.fi_FI
{
    using Windows.ApplicationModel.Resources;
    
    
    public sealed partial class AppResources
    {
        
        private static ResourceLoader resourceLoader;
        
        /// <summary>
        /// Get or set ResourceLoader implementation
        /// </summary>
        public static ResourceLoader Resource
        {
            get
            {
                if ((resourceLoader == null))
                {
                    AppResources.Initialize();
                }
                return resourceLoader;
            }
            set
            {
                resourceLoader = value;
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Lisää suosikki"
        /// </summary>
        public static string AddOrEditFavoriteDialog_AddHeader
        {
            get
            {
                return Resource.GetString("AddOrEditFavoriteDialog_AddHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Peruuta"
        /// </summary>
        public static string AddOrEditFavoriteDialog_Cancel
        {
            get
            {
                return Resource.GetString("AddOrEditFavoriteDialog_Cancel");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Muokkaa suosikkia"
        /// </summary>
        public static string AddOrEditFavoriteDialog_EditHeader
        {
            get
            {
                return Resource.GetString("AddOrEditFavoriteDialog_EditHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Kuvake"
        /// </summary>
        public static string AddOrEditFavoriteDialog_IconsHeader
        {
            get
            {
                return Resource.GetString("AddOrEditFavoriteDialog_IconsHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Tallenna"
        /// </summary>
        public static string AddOrEditFavoriteDialog_Save
        {
            get
            {
                return Resource.GetString("AddOrEditFavoriteDialog_Save");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sijainti"
        /// </summary>
        public static string AddOrEditFavoriteDialog_SearchBoxHeader
        {
            get
            {
                return Resource.GetString("AddOrEditFavoriteDialog_SearchBoxHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Nimi"
        /// </summary>
        public static string AddOrEditFavoriteDialog_UserChosenNameHeader
        {
            get
            {
                return Resource.GetString("AddOrEditFavoriteDialog_UserChosenNameHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Koskee"
        /// </summary>
        public static string AlertsPage_Affects
        {
            get
            {
                return Resource.GetString("AlertsPage_Affects");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Lähtöaika:"
        /// </summary>
        public static string AlertsPage_TimeEnd
        {
            get
            {
                return Resource.GetString("AlertsPage_TimeEnd");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Saapumisaika:"
        /// </summary>
        public static string AlertsPage_TimeStart
        {
            get
            {
                return Resource.GetString("AlertsPage_TimeStart");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Tarkastele verkossa"
        /// </summary>
        public static string AlertsPage_ViewOnline
        {
            get
            {
                return Resource.GetString("AlertsPage_ViewOnline");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Trippit helpottaa julkisen liikenteen käyttöä pääkaupunkiseudulla."
        /// </summary>
        public static string AppDescription
        {
            get
            {
                return Resource.GetString("AppDescription");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Trippit"
        /// </summary>
        public static string AppName
        {
            get
            {
                return Resource.GetString("AppName");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Tänään"
        /// </summary>
        public static string CurrentDatePicker_CurrentDate
        {
            get
            {
                return Resource.GetString("CurrentDatePicker_CurrentDate");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Nyt"
        /// </summary>
        public static string CurrentTimePicker_CurrentTime
        {
            get
            {
                return Resource.GetString("CurrentTimePicker_CurrentTime");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Tumma"
        /// </summary>
        public static string DarkThemeName
        {
            get
            {
                return Resource.GetString("DarkThemeName");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Reittejä ei löytynyt. Tarkista hakuehdot."
        /// </summary>
        public static string DialogMessage_NoTripsFoundNoResults
        {
            get
            {
                return Resource.GetString("DialogMessage_NoTripsFoundNoResults");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Reittejä ei löytynyt, koska yhteyttä palvelimeen ei ole käytettävissä. Tarkista verkkoasetuksesi tai yritä myöhemmin uudelleen."
        /// </summary>
        public static string DialogMessage_NoTripsFoundNoServer
        {
            get
            {
                return Resource.GetString("DialogMessage_NoTripsFoundNoServer");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Tietoja ei saatu palvelimelta. Palvelu ei ole käytettävissä. Yritä myöhemmin uudelleen."
        /// </summary>
        public static string DialogMessage_NoTripsFoundServerDown
        {
            get
            {
                return Resource.GetString("DialogMessage_NoTripsFoundServerDown");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Reittejä ei löytynyt. Yritä uudelleen."
        /// </summary>
        public static string DialogMessage_NoTripsFoundUnknown
        {
            get
            {
                return Resource.GetString("DialogMessage_NoTripsFoundUnknown");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Seuraavia ei löytynyt:"
        /// </summary>
        public static string DialogMessage_PlaceResolutionFailed
        {
            get
            {
                return Resource.GetString("DialogMessage_PlaceResolutionFailed");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sijaintiasi ei löytynyt. Varmista, että olet antanut tälle sovellukselle luvan käyttää laitteesi paikannusta."
        /// </summary>
        public static string DialogMessage_UserLocationFailed
        {
            get
            {
                return Resource.GetString("DialogMessage_UserLocationFailed");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Virhe paikannuksessa"
        /// </summary>
        public static string DialogTitle_NoLocationFound
        {
            get
            {
                return Resource.GetString("DialogTitle_NoLocationFound");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Reittejä ei löytynyt"
        /// </summary>
        public static string DialogTitle_NoTripsFound
        {
            get
            {
                return Resource.GetString("DialogTitle_NoTripsFound");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Lisää suosikki"
        /// </summary>
        public static string FavoritesPage_CommandBarAddFavorite
        {
            get
            {
                return Resource.GetString("FavoritesPage_CommandBarAddFavorite");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Poista valitut"
        /// </summary>
        public static string FavoritesPage_CommandBarDeleteSelected
        {
            get
            {
                return Resource.GetString("FavoritesPage_CommandBarDeleteSelected");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Valitse"
        /// </summary>
        public static string FavoritesPage_CommandBarSelect
        {
            get
            {
                return Resource.GetString("FavoritesPage_CommandBarSelect");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "SUOSIKIT"
        /// </summary>
        public static string FavoritesPage_PageHeader
        {
            get
            {
                return Resource.GetString("FavoritesPage_PageHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Et ole vielä tallentanut yhtään suosikkia"
        /// </summary>
        public static string Favorites_EmptyList
        {
            get
            {
                return Resource.GetString("Favorites_EmptyList");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Suosikit"
        /// </summary>
        public static string Favorites_FavoritesHeader
        {
            get
            {
                return Resource.GetString("Favorites_FavoritesHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "on jo kiinnitetty Aloitukseen!"
        /// </summary>
        public static string Favorites_PinToStartAlreadyExists
        {
            get
            {
                return Resource.GetString("Favorites_PinToStartAlreadyExists");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Kiinnitys Aloitukseen ei onnistunut"
        /// </summary>
        public static string Favorites_PinToStartErrorTitle
        {
            get
            {
                return Resource.GetString("Favorites_PinToStartErrorTitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Jotakin meni pieleen, kohteen {0} kiinnittäminen Aloitukseen ei onnistunut."
        /// </summary>
        public static string Favorites_PinToStartGenericFailure
        {
            get
            {
                return Resource.GetString("Favorites_PinToStartGenericFailure");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Paikat"
        /// </summary>
        public static string Favorites_PlacesGroupHeader
        {
            get
            {
                return Resource.GetString("Favorites_PlacesGroupHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Reitit"
        /// </summary>
        public static string Favorites_RoutesGroupHeader
        {
            get
            {
                return Resource.GetString("Favorites_RoutesGroupHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Lisää suosikkeihin"
        /// </summary>
        public static string Flyout_AddToFavorites
        {
            get
            {
                return Resource.GetString("Flyout_AddToFavorites");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Muokkaa"
        /// </summary>
        public static string Flyout_Edit
        {
            get
            {
                return Resource.GetString("Flyout_Edit");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Etusivu"
        /// </summary>
        public static string Flyout_MainPage
        {
            get
            {
                return Resource.GetString("Flyout_MainPage");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Kiinnitä..."
        /// </summary>
        public static string Flyout_PinTo
        {
            get
            {
                return Resource.GetString("Flyout_PinTo");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Valitse"
        /// </summary>
        public static string Flyout_Select
        {
            get
            {
                return Resource.GetString("Flyout_Select");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Aseta kohteeksi"
        /// </summary>
        public static string Flyout_SetAsDestination
        {
            get
            {
                return Resource.GetString("Flyout_SetAsDestination");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Aseta lähtöpaikaksi"
        /// </summary>
        public static string Flyout_SetAsOrigin
        {
            get
            {
                return Resource.GetString("Flyout_SetAsOrigin");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Aloitus"
        /// </summary>
        public static string Flyout_Start
        {
            get
            {
                return Resource.GetString("Flyout_Start");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Vaalea"
        /// </summary>
        public static string LightThemeName
        {
            get
            {
                return Resource.GetString("LightThemeName");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Peruuta"
        /// </summary>
        public static string LiteralCancel
        {
            get
            {
                return Resource.GetString("LiteralCancel");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Päiväys"
        /// </summary>
        public static string LiteralDate
        {
            get
            {
                return Resource.GetString("LiteralDate");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Poista"
        /// </summary>
        public static string LiteralDelete
        {
            get
            {
                return Resource.GetString("LiteralDelete");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Nyt"
        /// </summary>
        public static string LiteralNow
        {
            get
            {
                return Resource.GetString("LiteralNow");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Kiinnitä Aloitukseen"
        /// </summary>
        public static string LiteralPinToStart
        {
            get
            {
                return Resource.GetString("LiteralPinToStart");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Aika"
        /// </summary>
        public static string LiteralTime
        {
            get
            {
                return Resource.GetString("LiteralTime");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Ladataan..."
        /// </summary>
        public static string LoadingLiteral
        {
            get
            {
                return Resource.GetString("LoadingLiteral");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Hälytykset"
        /// </summary>
        public static string MainPageHeaderCommand_Alerts
        {
            get
            {
                return Resource.GetString("MainPageHeaderCommand_Alerts");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "+ Lisää välipysäkki"
        /// </summary>
        public static string MainPage_AddIntermediateDestination
        {
            get
            {
                return Resource.GetString("MainPage_AddIntermediateDestination");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Lähtöpaikka"
        /// </summary>
        public static string MainPage_FromHeader
        {
            get
            {
                return Resource.GetString("MainPage_FromHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "MATKAN SUUNNITTELU"
        /// </summary>
        public static string MainPage_Header
        {
            get
            {
                return Resource.GetString("MainPage_Header");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Huom! Valittu päivämäärä ja aika ovat jo menneet."
        /// </summary>
        public static string MainPage_TimeInPastWarning
        {
            get
            {
                return Resource.GetString("MainPage_TimeInPastWarning");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Kohde"
        /// </summary>
        public static string MainPage_ToHeader
        {
            get
            {
                return Resource.GetString("MainPage_ToHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Suosikit"
        /// </summary>
        public static string NavigationLabels_Favorites
        {
            get
            {
                return Resource.GetString("NavigationLabels_Favorites");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Etusivu"
        /// </summary>
        public static string NavigationLabels_Home
        {
            get
            {
                return Resource.GetString("NavigationLabels_Home");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Haku"
        /// </summary>
        public static string NavigationLabels_Search
        {
            get
            {
                return Resource.GetString("NavigationLabels_Search");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Asetukset"
        /// </summary>
        public static string NavigationLabels_Settings
        {
            get
            {
                return Resource.GetString("NavigationLabels_Settings");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Poista"
        /// </summary>
        public static string PinnedFavoritesList_Unpin
        {
            get
            {
                return Resource.GetString("PinnedFavoritesList_Unpin");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "HAKU"
        /// </summary>
        public static string SearchPage_Header
        {
            get
            {
                return Resource.GetString("SearchPage_Header");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Linjat"
        /// </summary>
        public static string SearchPage_LinesHeader
        {
            get
            {
                return Resource.GetString("SearchPage_LinesHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Hae pysäkkejä lähellä minua"
        /// </summary>
        public static string SearchPage_MapContextFindPlacesAtMe
        {
            get
            {
                return Resource.GetString("SearchPage_MapContextFindPlacesAtMe");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Hae pysäkkejä lähellä tätä sijaintia"
        /// </summary>
        public static string SearchPage_MapContextMenuFindPlacesHere
        {
            get
            {
                return Resource.GetString("SearchPage_MapContextMenuFindPlacesHere");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Lähellä"
        /// </summary>
        public static string SearchPage_NearbyHeader
        {
            get
            {
                return Resource.GetString("SearchPage_NearbyHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Pysäkit"
        /// </summary>
        public static string SearchPage_StopsHeader
        {
            get
            {
                return Resource.GetString("SearchPage_StopsHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sallimalla tämän sovellus lähettää nimettömiä tietoja sovelluksen kehittäjälle. Hän voi käyttää tietoja sovelluksen kehittämiseen tai käyttämättömien ominaisuuksien poistamiseen! Kiitos avusta! =)"
        /// </summary>
        public static string SettingsPage_AnalyticsExplanation
        {
            get
            {
                return Resource.GetString("SettingsPage_AnalyticsExplanation");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Analytiikka ja teletiedot"
        /// </summary>
        public static string SettingsPage_AnalyticsHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_AnalyticsHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Seuranta"
        /// </summary>
        public static string SettingsPage_AnalyticsToggleHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_AnalyticsToggleHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Voit asettaa oletuskohteen ja -lähtöpaikan, sekä reitin oletusasetukset. Näitä asetuksia käytetään etusivulla, kun sovellus avataan."
        /// </summary>
        public static string SettingsPage_DefaultSearchExplanation
        {
            get
            {
                return Resource.GetString("SettingsPage_DefaultSearchExplanation");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Oletushakuehdot"
        /// </summary>
        public static string SettingsPage_DefaultSearchHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_DefaultSearchHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Aseta etusivulle kiinnitettyjen suosikkien maksimimäärä. Oletus: 3"
        /// </summary>
        public static string SettingsPage_FavoritesPanelExplanation
        {
            get
            {
                return Resource.GetString("SettingsPage_FavoritesPanelExplanation");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Suosikit"
        /// </summary>
        public static string SettingsPage_FavoritesPanelHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_FavoritesPanelHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Lähtöpaikka"
        /// </summary>
        public static string SettingsPage_FromBoxHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_FromBoxHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Lisenssit"
        /// </summary>
        public static string SettingsPage_LicensesHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_LicensesHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "• Roslynator Apache 2.0 -lisenssillä
        ///• Template10 Apache 2.0 -lisenssillä
        ///• HockeyApp SDK MIT-lisenssillä
        ///• MetroLog MIT-lisenssillä
        ///• XAML Behaviors -kirjasto MIT-lisenssillä
        ///• MVVM Light MIT-lisenssillä
        ///• JSON.NET MIT-lisenssillä
        ///• NotificationExtensions -kirjasto MIT-lisenssillä"
        /// </summary>
        public static string SettingsPage_LicensesText
        {
            get
            {
                return Resource.GetString("SettingsPage_LicensesText");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "ASETUKSET"
        /// </summary>
        public static string SettingsPage_PageHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_PageHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Kiinnitettyjen suosikkien määrä"
        /// </summary>
        public static string SettingsPage_PinnedFavoritesNumberComboBoxHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_PinnedFavoritesNumberComboBoxHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Erityiskiitokset"
        /// </summary>
        public static string SettingsPage_SpecialThanksHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_SpecialThanksHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "• Kaisa. Miksi? Siksi! ??
        ///• Olli Saarikivi, oivallisesta Reitit-sovelluksesta ja vapaasti kylvetystä avusta
        ///• Alisa Suorava, fantastisesta sovelluskuvakkeesta
        ///• Teemu Turunen ja kaikki muut, joiden myötävaikutuksella Futurice Spice Program on syntynyt ja kehittynyt sellaiseksi kuin se on
        ///• HSL, avoimesta API:sta ja runsaasta resurssitarjonnasta
        ///• Sinä! Siitä, että käytät tätä sovellusta!"
        /// </summary>
        public static string SettingsPage_SpecialThanksText
        {
            get
            {
                return Resource.GetString("SettingsPage_SpecialThanksText");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Näytön teema"
        /// </summary>
        public static string SettingsPage_ThemeComboBoxHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_ThemeComboBoxHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Aseta sovelluksen teema"
        /// </summary>
        public static string SettingsPage_ThemeExplanation
        {
            get
            {
                return Resource.GetString("SettingsPage_ThemeExplanation");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Teema"
        /// </summary>
        public static string SettingsPage_ThemeHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_ThemeHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Kohde"
        /// </summary>
        public static string SettingsPage_ToBoxHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_ToBoxHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Versio"
        /// </summary>
        public static string SettingsPage_VersionHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_VersionHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Kävelyn määrä"
        /// </summary>
        public static string SettingsPage_WalkingAmountHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_WalkingAmountHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Kävelynopeus"
        /// </summary>
        public static string SettingsPage_WalkingSpeedHeader
        {
            get
            {
                return Resource.GetString("SettingsPage_WalkingSpeedHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Tulevat lähdöt"
        /// </summary>
        public static string StopSearchContent_DetailsDeparturesHeader
        {
            get
            {
                return Resource.GetString("StopSearchContent_DetailsDeparturesHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Näyttää siltä, ettei tänään ole enää tulevia lähtöjä"
        /// </summary>
        public static string StopSearchContent_DetailsEmptyDeparturesListHeader
        {
            get
            {
                return Resource.GetString("StopSearchContent_DetailsEmptyDeparturesListHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Linjat"
        /// </summary>
        public static string StopSearchContent_DetailsLinesHeader
        {
            get
            {
                return Resource.GetString("StopSearchContent_DetailsLinesHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Tarkastele pysäkin tietoja"
        /// </summary>
        public static string StopSearchElement_ViewDetails
        {
            get
            {
                return Resource.GetString("StopSearchElement_ViewDetails");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Osoitteet"
        /// </summary>
        public static string SuggestBoxHeader_Addresses
        {
            get
            {
                return Resource.GetString("SuggestBoxHeader_Addresses");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Suosikit"
        /// </summary>
        public static string SuggestBoxHeader_FavoritePlaces
        {
            get
            {
                return Resource.GetString("SuggestBoxHeader_FavoritePlaces");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sijaintini"
        /// </summary>
        public static string SuggestBoxHeader_MyLocation
        {
            get
            {
                return Resource.GetString("SuggestBoxHeader_MyLocation");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Pysäkit"
        /// </summary>
        public static string SuggestBoxHeader_TransitStops
        {
            get
            {
                return Resource.GetString("SuggestBoxHeader_TransitStops");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Järjestelmän teema"
        /// </summary>
        public static string SystemSettingThemeName
        {
            get
            {
                return Resource.GetString("SystemSettingThemeName");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Saapumisaika"
        /// </summary>
        public static string TimeType_Arrival
        {
            get
            {
                return Resource.GetString("TimeType_Arrival");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Lähtöaika"
        /// </summary>
        public static string TimeType_Departure
        {
            get
            {
                return Resource.GetString("TimeType_Departure");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Ei kiitos"
        /// </summary>
        public static string TooFarIntoPastDialog_Cancel
        {
            get
            {
                return Resource.GetString("TooFarIntoPastDialog_Cancel");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Kyllä!"
        /// </summary>
        public static string TooFarIntoPastDialog_Confirm
        {
            get
            {
                return Resource.GetString("TooFarIntoPastDialog_Confirm");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Olet valinnut menneen ajankohdan. Haluaisitko siirtää matkasi päivämäärän huomiselle?"
        /// </summary>
        public static string TooFarIntoPastDialog_Content
        {
            get
            {
                return Resource.GetString("TooFarIntoPastDialog_Content");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Älä näytä tätä enää"
        /// </summary>
        public static string TooFarIntoPastDialog_DontShowCheckbox
        {
            get
            {
                return Resource.GetString("TooFarIntoPastDialog_DontShowCheckbox");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Matkasi päivämäärä siirretään jatkossa seuraavalle päivälle, jos valitset menneen ajankohdan."
        /// </summary>
        public static string TooFarIntoPastDialog_DontShowInfo
        {
            get
            {
                return Resource.GetString("TooFarIntoPastDialog_DontShowInfo");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Oletko aikamatkustaja?"
        /// </summary>
        public static string TooFarIntoPastDialog_Title
        {
            get
            {
                return Resource.GetString("TooFarIntoPastDialog_Title");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "välipysäkki(ä)"
        /// </summary>
        public static string TripDetailListIntermediates_IntermediateStopsNumber
        {
            get
            {
                return Resource.GetString("TripDetailListIntermediates_IntermediateStopsNumber");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Matkusta {0} metriä"
        /// </summary>
        public static string TripDetailListIntermediates_TransitDistance
        {
            get
            {
                return Resource.GetString("TripDetailListIntermediates_TransitDistance");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Kävele {0} metriä"
        /// </summary>
        public static string TripDetailListIntermediates_WalkDistance
        {
            get
            {
                return Resource.GetString("TripDetailListIntermediates_WalkDistance");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Vähemmän valintoja"
        /// </summary>
        public static string TripForm_FewerOptions
        {
            get
            {
                return Resource.GetString("TripForm_FewerOptions");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Lisää valintoja"
        /// </summary>
        public static string TripForm_MoreOptions
        {
            get
            {
                return Resource.GetString("TripForm_MoreOptions");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Kiinnitetyt suosikit"
        /// </summary>
        public static string TripForm_PinnedFavoritesHeader
        {
            get
            {
                return Resource.GetString("TripForm_PinnedFavoritesHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Suunnittele matka"
        /// </summary>
        public static string TripForm_PlanATripHeader
        {
            get
            {
                return Resource.GetString("TripForm_PlanATripHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Suunnitellaan..."
        /// </summary>
        public static string TripForm_PlanningTrip
        {
            get
            {
                return Resource.GetString("TripForm_PlanningTrip");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Suunnittele"
        /// </summary>
        public static string TripForm_PlanTripButton
        {
            get
            {
                return Resource.GetString("TripForm_PlanTripButton");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Aseta tälle päivälle"
        /// </summary>
        public static string TripForm_SetDateToNow
        {
            get
            {
                return Resource.GetString("TripForm_SetDateToNow");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Aseta ajaksi nyt"
        /// </summary>
        public static string TripForm_SetTimeToNow
        {
            get
            {
                return Resource.GetString("TripForm_SetTimeToNow");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Kulkuvälineet"
        /// </summary>
        public static string TripForm_TransitTypeHeader
        {
            get
            {
                return Resource.GetString("TripForm_TransitTypeHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Kävelyn määrä"
        /// </summary>
        public static string TripForm_WalkingAmountHeader
        {
            get
            {
                return Resource.GetString("TripForm_WalkingAmountHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Kävelynopeus"
        /// </summary>
        public static string TripForm_WalkingSpeedHeader
        {
            get
            {
                return Resource.GetString("TripForm_WalkingSpeedHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Haetaan sijainteja..."
        /// </summary>
        public static string TripFrom_GettingsAddresses
        {
            get
            {
                return Resource.GetString("TripFrom_GettingsAddresses");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Kohde"
        /// </summary>
        public static string TripPlanStrip_EndPlaceDefault
        {
            get
            {
                return Resource.GetString("TripPlanStrip_EndPlaceDefault");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Lähtöpaikka"
        /// </summary>
        public static string TripPlanStrip_StartingPlaceDefault
        {
            get
            {
                return Resource.GetString("TripPlanStrip_StartingPlaceDefault");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Tarkemmat tiedot"
        /// </summary>
        public static string TripResultCommandBar_Details
        {
            get
            {
                return Resource.GetString("TripResultCommandBar_Details");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Kartta"
        /// </summary>
        public static string TripResultCommandBar_Map
        {
            get
            {
                return Resource.GetString("TripResultCommandBar_Map");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Tallenna reitti"
        /// </summary>
        public static string TripResults_SaveRoute
        {
            get
            {
                return Resource.GetString("TripResults_SaveRoute");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Matkasuunnitelmat"
        /// </summary>
        public static string TripResults_TripPlansHeader
        {
            get
            {
                return Resource.GetString("TripResults_TripPlansHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Mahdollisimman vähän"
        /// </summary>
        public static string WalkingAmount_0
        {
            get
            {
                return Resource.GetString("WalkingAmount_0");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Vähän"
        /// </summary>
        public static string WalkingAmount_1
        {
            get
            {
                return Resource.GetString("WalkingAmount_1");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Normaali"
        /// </summary>
        public static string WalkingAmount_2
        {
            get
            {
                return Resource.GetString("WalkingAmount_2");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Paljon"
        /// </summary>
        public static string WalkingAmount_3
        {
            get
            {
                return Resource.GetString("WalkingAmount_3");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Mahdollisimman paljon"
        /// </summary>
        public static string WalkingAmount_4
        {
            get
            {
                return Resource.GetString("WalkingAmount_4");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Etana kurvissa"
        /// </summary>
        public static string WalkingSpeed_0
        {
            get
            {
                return Resource.GetString("WalkingSpeed_0");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "30 m/min"
        /// </summary>
        public static string WalkingSpeed_0_Subtitle
        {
            get
            {
                return Resource.GetString("WalkingSpeed_0_Subtitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Hidas"
        /// </summary>
        public static string WalkingSpeed_1
        {
            get
            {
                return Resource.GetString("WalkingSpeed_1");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "50 m/min"
        /// </summary>
        public static string WalkingSpeed_1_Subtitle
        {
            get
            {
                return Resource.GetString("WalkingSpeed_1_Subtitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Normaali"
        /// </summary>
        public static string WalkingSpeed_2
        {
            get
            {
                return Resource.GetString("WalkingSpeed_2");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "72 m/min"
        /// </summary>
        public static string WalkingSpeed_2_Subtitle
        {
            get
            {
                return Resource.GetString("WalkingSpeed_2_Subtitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Reipas"
        /// </summary>
        public static string WalkingSpeed_3
        {
            get
            {
                return Resource.GetString("WalkingSpeed_3");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "125 m/min"
        /// </summary>
        public static string WalkingSpeed_3_Subtitle
        {
            get
            {
                return Resource.GetString("WalkingSpeed_3_Subtitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "KIIRE!"
        /// </summary>
        public static string WalkingSpeed_4
        {
            get
            {
                return Resource.GetString("WalkingSpeed_4");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "180 m/min"
        /// </summary>
        public static string WalkingSpeed_4_Subtitle
        {
            get
            {
                return Resource.GetString("WalkingSpeed_4_Subtitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "HÄLYTYKSET"
        /// </summary>
        public static string AlertsPage_PageHeader
        {
            get
            {
                return Resource.GetString("AlertsPage_PageHeader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Aseta reittisi"
        /// </summary>
        public static string Flyout_SetAsRoute
        {
            get
            {
                return Resource.GetString("Flyout_SetAsRoute");
            }
        }
        
        public static void Initialize()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(AppResources).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("AppResources");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/AppResources");
            }
        }
    }
}
